# command line: st_gcn_hcp/main.py recognition -c st_gcn_hcp/config/st_gcn/hcp_1200/train.yaml

base_lr: 0.1
batch_size: 20
config: st_gcn_hcp/config/st_gcn/hcp_1200/train.yaml
debug: false
device:
- 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 1
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 1
    num_class: 15
nesterov: true
num_epoch: 5
num_worker: 0
optimizer: SGD
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: true
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 30
- 40
- 50
test_batch_size: 5
test_feeder_args:
    data_path: ../test_data_age_5.npy
    label_path: ../test_label_5.pkl
train_feeder_args:
    data_path: ../train_data_age_5.npy
    label_path: ../train_label_5.pkl
    random_choose: true
    random_move: true
    window_size: 150
use_gpu: false
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/recognition/hcp_1200/ST_GCN
