weights: ./work_dir/recognition/hcp_1200/ST_GCN/epoch1_100_age_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ../test_data_age_100.npy
  label_path: ../test_label_100.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 1
  num_class: 15
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# test
phase: test
device: 0
test_batch_size: 20
