weights: ./work_dir/recognition/hcp_1200/ST_GCN/epoch44_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ../test_data.npy
  label_path: ../test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 1
  num_class: 2
  edge_importance_weighting: True

# test
phase: test
device: 0
test_batch_size: 64
