weights: ./work_dir/recognition/hcp_1200/ST_GCN/epoch100_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ../data/test_data_no_aug.npy
  label_path: ../data/test_label_no_aug.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 1
  num_class: 2
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# test
phase: test
device: 0
test_batch_size: 64
