work_dir: ./work_dir/recognition/hcp_1200/ST_GCN
use_gpu: False
eval_interval: 1

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 25
  data_path: ../aws/train_data.npy
  label_path: ../aws/train_label.pkl
test_feeder_args:
  data_path: ../aws/dev_data.npy
  label_path: ../aws/dev_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 1
  num_class: 16
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0]
batch_size: 64
test_batch_size: 64

#optim
base_lr: 0.01
step: [200]
num_epoch: 200
optimizer: 'Adam'
