work_dir: ./work_dir/recognition/hcp_1200/ST_GCN
use_gpu: False


# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150
  data_path: ../aws_train_data_age.npy
  label_path: ../aws_train_label_age.pkl
test_feeder_args:
  data_path: ../aws_test_data_age.npy
  label_path: ../aws_test_label_age.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 1
  num_class: 15
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0]
batch_size: 64
test_batch_size: 5

#optim
base_lr: 0.1
step: [3,6]
num_epoch: 10
