work_dir: ./work_dir/recognition/hcp_1200/ST_GCN
use_gpu: False
eval_interval: 1

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150
  data_path: ../train_data_age_100.npy
  label_path: ../train_label_100.pkl
test_feeder_args:
  data_path: ../train_data_age_100.npy
  label_path: ../train_label_100.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 1
  num_class: 16
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0]
batch_size: 16
test_batch_size: 5

#optim
base_lr: 0.1
step: [3,6]
num_epoch: 2
