work_dir: ./work_dir/recognition/hcp_1200/ST_GCN
use_gpu: True
eval_interval: 1

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 30
  data_path: ../data/train_data_22_sex_100.npy
  label_path: ../data/train_label_22_sex_100.pkl
test_feeder_args:
  data_path: ../data/test_data_22_sex_100.npy
  label_path: ../data/test_label_22_sex_100.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 1
  num_class: 2
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0]
batch_size: 64
test_batch_size: 64

#optim
base_lr: 0.001
step: [99]
num_epoch: 100
